package clients;

public class Client
{
    private String firstName;
    private String lastName;
    // TODO : long
    private int id;
    private generatedId = 0;

    /**
     * Getter
     * @return firstName
     */
    public String getFirstName()
    {
        return firstName;
    }

    /**
     * Setter
     * @param firstName
     */
    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    /**
     * Getter
     * @return lastName
     */
    public String getLastName()
    {
        return lastName;
    }

    /**
     * Setter
     * @param lastName
     */
    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    /**
     * Getter
     * @return id
     */
    public int getId()
    {
        return id;
    }

    /**
     * Setter
     * @param id
     */
    public void setId(int id)
    {
        this.id = id;
    }

    /**
     * Client constructor
     *
     * Setting firstName and lastName, id is generated by increasing static int attribute.
     * @param firstName
     * @param lastName
     */
    public Client(String firstName, String lastName)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.id = generatedId++;
    }
}
